### ISSUE TITLE
Mask passwords in App Manager

### ISSUE THREAD

**Issue by varontron** [Novartis/YADA#53]

**Comment by christopheleroy** [comment]
I can imagine this would be mostly a trick in the Admin UI - that would be great.

I'm also interested in working on masking the passwords, but even in the database where it eventually resides.
e.g. the WEB-INF/classes/YADA.properties would have 2 new properties:

YADA.index.secured=false|true
YADA.index.encryption-key=some base64 encoded stretch of data of at least 128 bits

the encryption would use a salt to make it safe.

Thinking about this, this would also require a new pre-processor plug-in that forces the encryption on "YADA new query" and "YADA update query".
The way it would do this:
 - read the YADA_QUERY_CONF.CONF value, 
 - split in lines
 - for attribute 'encpassword', decrypt the encrypted password, remove the encpassword attribute and add the decpassword attribute with that value
-- ON read for Yada Admin, remove the decpassword attribute and remove the password attribute if there, leave the encpassword for everyone to see
-- ON read for ConnectionFactory, if there is an encpassword attribute, remove it, remove the password attribute if it is there, and rename the decpassword attribute to password, to pass to Hikari.
-- ON write from Yada Admin, if there is a password attribute, encrypt the password value, remove the password attribute, remove the encpassword if it is there and add the encpassword attribute the encrypted password value
-- reassemble the lines into the multiline string that is CONF.
-- the cache and connection factory would still see the 'password' attribute with the decrypted/native value.

That way:
 - you can start with a db that is not encrypted
 - you turn on encryption and reboot tomcat
 - you can continue using the yada server without going through the re-encrypting of the connection passwords
 - we can later have a tool, but to make these password encrypted, you'd simply go in the Yada admin and key them in again, one by one :(

 - we can have another plug-in for the conversion of all connections - it would be only working from the properties YADA.index.encryption-key (with the new key) and YADA.index.former-key ...

Why I'm going with this ?
I find it reasonably safe to have passwords in plain text on local files of  a server (context.xml etc) that is well protected.
Obviously not very safe, but reasonable.
I find spreading the passwords to a remote service (such an Oracle server) is rather increasing the weaknesses.  
For safety nuts (like me) that acts as the boss of a Yada Adopter, this would provide some comfort...

**Comment by christopheleroy** [comment]
NX like Jasypt a lot, it would implemented the better part of my suggestion above.

**Comment by christopheleroy** [comment]
I'm rewriting my comment of April with Jasypt in mind:

I'm also interested in working on masking the passwords, but even in the database where it eventually resides.
e.g. the WEB-INF/classes/YADA.properties would have 2 new properties:

YADA.index.jasypt.encryption=[ one of the jasypt encryption schemes [PBEWITHMD5ANDDES, PBEWITHMD5ANDTRIPLEDES, PBEWITHSHA1ANDDESEDE, PBEWITHSHA1ANDRC2_40] - the default is the first one]

YADA.index.jasypt.encryption-key=the plain text of the encryption key for Jasypt, or the name of an environment variable that is expected to contain the encryption-key

(optionally: YADA.index.jasypt.encryption-iterations= the number of iteration for the encryptor, I think the default is 1000, but better leave it blank :) )
 

After that, ConnectionFactory::createJdbcDataSource would need to be altered to use some "EncryptableProperties" instead of "Properties" 
see http://www.jasypt.org/encrypting-configuration.html section EncryptableProperties



This does not encrypt the password magically, but if a SuperAdmin use the Yada Admin to edit the connection properties of an app, they can use the Jasypt convention to enter the encrypted password. (and even encrypted username) - they have to encrypt it themselves.
So, they'd find something like:
```
 datasource.driver=com.mysql.jdbc.Driver
 datasource.url=jdbc:mysql://localhost/reportsdb
 datasource.username=reportsUser
 datasource.password=reportsSuck
```
Use the jasypt command line utility:
./encrypt password=be-shadow input="reportsUser"
./encrypt password=be-shadow input="reportsSuck"

and manually replace the connection details:

```
 datasource.driver=com.mysql.jdbc.Driver
 datasource.url=jdbc:mysql://localhost/reportsdb
 datasource.username=ENC(Ufin1X1RpoMaZCzw/Cj9cMdhyYeevc37)
 datasource.password=ENC(on+JbHpj5Aq+Z1cZwU/6ciJQJDZ38NLE)
```

The EncyptableProperties should be decrypting them on the fly when HikariPool uses them.

**Comment by christopheleroy** [comment]
Added bonus - one could probably easily encrypt with Jasypt's simpler approach in Javascript, in the Yada Admin UI, offering the SuperAdmin the ability to do it there already. 
They'll have to be careful to user the right encryption key for their server
This page has the decryption in node.js
https://github.com/Confluex/Zuul/wiki/Encryption

the Crypto module is almost surely easy to bring to the browser.

**Comment by varontron** [comment]
This request now obsolete in lieu of the following:
* YADA supports conventional login security like arbitrary cred store integration, including SAML
* YADA issues a JWT at login and validates it on every request
* By default YADA passwords are salted and encrypted with argon2
* The YADA index is now a git repo not a database
